// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwzENtcYqE21lvCEqdNHXPxqQHtTbNxWY',
    appId: '1:170775697809:web:b08e9ea3f98853b8d86230',
    messagingSenderId: '170775697809',
    projectId: 'test-bionic-app',
    authDomain: 'test-bionic-app.firebaseapp.com',
    storageBucket: 'test-bionic-app.appspot.com',
    measurementId: 'G-863R4DNQC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf_s8lSli0cXJcJpUmQ2zG5WBYIGKbM9c',
    appId: '1:170775697809:android:db1045beb33aacaad86230',
    messagingSenderId: '170775697809',
    projectId: 'test-bionic-app',
    storageBucket: 'test-bionic-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0IKITfgh1CYIQWflI3mmDeErRRVV2M-0',
    appId: '1:170775697809:ios:d3e6daa84d9118d9d86230',
    messagingSenderId: '170775697809',
    projectId: 'test-bionic-app',
    storageBucket: 'test-bionic-app.appspot.com',
    iosClientId: '170775697809-tk8b2av98hsr2oa9fsi9g9u8irqr2t5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.testBionicApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0IKITfgh1CYIQWflI3mmDeErRRVV2M-0',
    appId: '1:170775697809:ios:774d3223878a8c13d86230',
    messagingSenderId: '170775697809',
    projectId: 'test-bionic-app',
    storageBucket: 'test-bionic-app.appspot.com',
    iosClientId: '170775697809-upa4ovj3dpu87lnv8s1dvs1f1j4ooram.apps.googleusercontent.com',
    iosBundleId: 'com.example.testBionicApp2.RunnerTests',
  );
}
